"""empty message

Revision ID: 37be2c225209
Revises: d1e0e2249287
Create Date: 2023-02-02 14:29:04.135709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37be2c225209'
down_revision = 'd1e0e2249287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
